# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqzTALdg8v-nZEu8MuxpaPYf3w4BhuLB
"""

import streamlit as st
import openai
import fitz  # PyMuPDF
import os

st.set_page_config(page_title="AI Interview Bot", layout="centered")
openai.api_key = "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"  # Replace with your OpenAI key

def extract_text_from_resume(file):
    with open("temp_resume.pdf", "wb") as f:
        f.write(file.read())
    doc = fitz.open("temp_resume.pdf")
    return "\n".join(page.get_text() for page in doc)

# ================== Helper: Generate questions ==================
def generate_questions(resume_text, jd_text):
    prompt = f"""
You are an intelligent interview bot. Based on the job description and resume, generate 5 technical and 3 behavioral interview questions.

Job Description:
{jd_text}

Resume:
{resume_text}

Return only the list of questions in bullet points.
"""
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

st.title("🤖 AI Video Interview Question Generator")

jd_input = st.text_area("📄 Paste the Job Description")

uploaded_file = st.file_uploader("📎 Upload Resume (PDF only)", type=["pdf"])

if st.button("Generate Questions"):
    if not uploaded_file or not jd_input.strip():
        st.warning("Please upload a resume and enter the job description.")
    else:
        resume_text = extract_text_from_resume(uploaded_file)
        with st.spinner("Generating questions..."):
            questions = generate_questions(resume_text, jd_input)
        st.success("✅ Questions generated!")
        st.markdown("### 🧠 Interview Questions")
        st.markdown(questions)

